### ISSUE TITLE
No CdrBlast matches even though manual BLAST works

### ISSUE THREAD

**Issue by wlchew** [mikessh/migec#15] opened 2015-08-18 14:23 UTC
Hi, I got to the stage of CdrBlast (checkout>histogram>assembly>...). However, running CdrBlast gives 0 mapped reads. I've previously used MiXCR with the fastq and it was successful, and I also BLASTed the assembly fastq and they were fine too. These are mouse TCRb RNA samples. Please see attached code below.

On a side note, is MIGEC sensitive to reverse complementarity? I have read1 reading from the constant region, and read2 reading from UMI adaptor into V region (ie, reverse complement of the usual).

Thank you in advance!

code on Windows command line========:

...\MIGEC>java -jar migec-1.2.1b.jar CdrBlast -a --al
l-alleles -debug -R TRB -S MusMusculus ./assembly/*_R2.t5.fastq.gz ./assembly/*_
R1.t5.fastq.gz ./cdrblast/cdrblast.txt
Executing com.milaboratory.migec.CdrBlast -a --all-alleles -debug -R TRB -S MusM
usculus assembly\UMIcounted_R2.t5.fastq.gz assembly\UMIcounted_R1.t5.fastq.gz ./
cdrblast/cdrblast.txt
[Tue Aug 18 10:06:20 EDT 2015 com.milaboratory.migec.CdrBlast] Loading TRB Varia
ble and Joining segment data
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Generating BLAST
database for TRB V
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Generating BLAST
database for TRB J
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Reading assembly\
UMIcounted_R2.t5.fastq.gz and generating list of unique sequences to map V and J
 genes
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Reading assembly\
UMIcounted_R1.t5.fastq.gz and generating list of unique sequences to map V and J
 genes
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Making a temporar
y FASTA file for BLAST queries
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Pre-aligning TRB
V segment with BLAST <12 threads>
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Pre-aligning TRB
J segment with BLAST <12 threads>
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Reading in BLAST
results
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done 0 V and 0 J
mapped, out of total 5650 sequence variants
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Extracting CDRs
Reporting 10 good and bad alignments
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done. 0 CDRs mapp
ed, out of total 5650 sequence variants
reverseFound=0 (0%)
badOrientation=0
vRefNotInAlignment=0
jRefNotInAlignment=0
cdrStartOut=0
cdrEndOut=0
shortCdr3=0 (<7 nt)
longCdr3=0 (>300 nt)
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done. Mapping Div
ersity segments
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Appending read da
ta from assembly\UMIcounted_R2.t5.fastq.gz
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Appending read da
ta from assembly\UMIcounted_R1.t5.fastq.gz
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Done
EVENTS (good mapped total):     0       0       6174    |       0%      0%
100%
READS (good mapped total):      0       0       182029  |       0%      0%
100%
[Tue Aug 18 10:06:21 EDT 2015 com.milaboratory.migec.CdrBlast] Writing output

**Comment by mikessh** [comment] 2015-08-18 16:20
Hi @wlchew 
This seems quite strange, as no single V and J segments are mapped (thats why no CDR3 are extracted). It could be smth with MusMusculus references here in MIGEC. Can you please provide several assembled reads (~10-100) and the same number of raw reads, so I can run some basic diagnostics for the problem.

**Comment by mikessh** [comment] 2015-08-19 19:36
Resolved in a private conversation. Not a bug, appears to be an issue with barcodes file.

**Comment by wlchew** [comment] 2015-08-31 15:27
To help out other users, @mikessh suggested that the issue might be windows-related. This is correct: after changing the environment to linux, alignments worked well.

**Comment by mikessh** [comment] 2015-09-01 00:56
Thank you!

**Closed by mikessh** 2015-09-01 00:56 UTC
